### ISSUE TITLE
bootstrap breaking on mac

### ISSUE THREAD

**Issue by nicolemarsaglia** [Alpine-DAV/ascent#165]
I'm running high sierra 10.13.6

The bootstrap breaks building hdf5. 

==> Installing hdf5
==> Using cached archive: /Users/nicolemarsaglia/Desktop/Ascent/ascent/uberenv_libs/spack/var/spack/cache/hdf5/hdf5-1.8.19.tar.gz
==> Staging archive: /Users/nicolemarsaglia/Desktop/Ascent/ascent/uberenv_libs/spack/var/spack/stage/hdf5-1.8.19-6shiep33xp3lpdws4zdirqqjne74gn2w/hdf5-1.8.19.tar.gz
==> Created stage in /Users/nicolemarsaglia/Desktop/Ascent/ascent/uberenv_libs/spack/var/spack/stage/hdf5-1.8.19-6shiep33xp3lpdws4zdirqqjne74gn2w
==> No patches needed for hdf5
==> Building hdf5 [AutotoolsPackage]
==> Executing phase: 'autoreconf'
==> Executing phase: 'configure'
==> Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j8'

4 errors found in build log:

     1454      CCLD     libdynlib4.la
     1455      CCLD     testhdf5
     1456      CCLD     lheap
     1457      CCLD     ohdr
     1458      CCLD     stab
     1459      CCLD     gheap
     1460    Undefined symbols for architecture x86_64:
     1461      "_H5E_CALLBACK_g", referenced from:
     1462          _H5Z_filter_dynlib4 in dynlib4.o
     1463      "_H5E_ERR_CLS_g", referenced from:
     1464          _H5Z_filter_dynlib4 in dynlib4.o
     1465      "_H5E_PLUGIN_g", referenced from:
     1466          _H5Z_filter_dynlib4 in dynlib4.o

     ...

     1468          _H5Z_filter_dynlib4 in dynlib4.o
     1469      "_H5get_libversion", referenced from:
     1470          _H5Z_filter_dynlib4 in dynlib4.o
     1471      "_H5open", referenced from:
     1472          _H5Z_filter_dynlib4 in dynlib4.o
     1473    ld: symbol(s) not found for architecture x86_64
     1474    clang: error: linker command failed with exit code 1 (use -v to se
             e invocation)
     1475    make[1]: *** [libdynlib4.la] Error 1
     1476    make[1]: *** Waiting for unfinished jobs....
     1477    make: *** [all-recursive] Error 1

See build log for details:
  /Users/nicolemarsaglia/Desktop/Ascent/ascent/uberenv_libs/spack/var/spack/stage/hdf5-1.8.19-6shiep33xp3lpdws4zdirqqjne74gn2w/hdf5-1.8.19/spack-build.out
[Active CMake: /Users/nicolemarsaglia/Desktop/Ascent/ascent/uberenv_libs/spack/opt/spack/darwin-highsierra-x86_64/clang-9.0.0-apple/cmake-3.9.6-xjoxbbktixhgzfyczhrrdhfgmrgoxvu4/bin/cmake ]

**Comment by cyrush** [comment]
Hmm, it seems hdf5 is unhappy with itself. Those missing symbols are (_H5Open, etc) are part of the standard hdf5 api.  Maybe something got corrupted during the build?

Can you see if it hit this again after deleting:
/Users/nicolemarsaglia/Desktop/Ascent/ascent/uberenv_libs/spack/var/spack/stage/hdf5-1.8.19-6shiep33xp3lpdws4zdirqqjne74gn2w/hdf5-1.8.19

**Comment by nicolemarsaglia** [comment]
Still hitting this error during the bootstrap after deleting the hdf5 build dir you pointed to.

**Comment by cyrush** [comment]
@nicolemarsaglia sorry for the delay. 

What version of Xcode are you using & which branch are you running bootstrap from?

On macOS 10.13.6 with XCode 9.2, using:

`source bootstrap-env.sh `

I didn't hit any hdf5 build issues. 


Is this a fresh build -- if not the spack fork may not be update to date?

**Comment by cyrush** [comment]
@nicolemarsaglia Gunther hit this issue as well. 

He mentioned he has XCode 10.1. 

I have 9.2

I suspect you have XCode 10.1 as well?

**Comment by nicolemarsaglia** [comment]
That must be it. I'm running 10.1.

**Comment by ghweber** [comment]
@nicolemarsaglia @cyrush 

I believe figured out the problem and got Ascent to run.

**Short version:**
  * Xcode 10.1 only comes with an SDK for 10.14, to compile on 10.13 you need to compile with installed files instead of the SDK
  * The current uberenv script forces using that SDK (function: setup_osx_sdk_env_vars)
  * The result are that built code does not always work on 10.13

**Workaround:**
Just disable picking a SDK in uberenv.py
```
--- a/scripts/uberenv/uberenv.py
+++ b/scripts/uberenv/uberenv.py
@@ -349,7 +349,8 @@ def main():
     # setup osx deployment target
     print "[uberenv options: %s]" % str(opts)
     if "darwin" in platform.system().lower():
-        setup_osx_sdk_env_vars()
+        pass
+        #setup_osx_sdk_env_vars()
     # setup default spec
     if opts["spec"] is None:
         if "darwin" in platform.system().lower():
```
and follow the instructions.

**Longer Discussion:**
I have been encountering the same problem with VisIt a couple of time. These days, Xcode only seems to come with an SDK for the current MacOS. Often this Xcode version also runs with the previous MacOS. For example Xcode 10.1 comes with the SDK for 10.14 but still runs on 10.13. Setting up SDK and MACOSX_DEPLOYMENT_TARGET breaks builds for the older MacOS version (10.13 here) in that scenario. Not to set these environment variables and let the compile tools use the regular version of libraries and includes from the regular OS install (e.g., ``/usr/lib`` instead of ``/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/lib``) fixes this problem.

It seems that the behavior for this has changed a while back, and I am not sure that the method we use for VisIt and here still apply to current versions of MacOS. For something like Conduit and Ascent, which is likely run on the same machine as it is built, it seems the method causing the least problems is to just not set these environment variables. For my VisIt workaround I detect certain Xcode/MacOS combinations and disable setting them only in these instances, but that may be overly complicated.

It would probably be worth doing some additional research to see if we want to remove this from Ascent/Conduit altogether. But in the meantime, this workaround seems to work.

[disable_osx_sdk.patch.txt](https://github.com/Alpine-DAV/ascent/files/2669994/disable_osx_sdk.patch.txt)

**Comment by cyrush** [comment]
thanks @ghweber! This is very helpful.  I'll ponder this a bit more. 

I think we forced the SDK version b/c of issues with older MacOSX versions, but maybe now we should stop. I may add it as an option to uberenv incase its still needed, but avoid doing it always.

**Comment by ghweber** [comment]
If it was there for older Mac versions then one approach may be to do it based on MacOS version. Looking at my workaround for VisIt in bv_vtk.sh, the first time the problem occurred was with MacOS 10.10 / Xcode 7). So you could just skip setting this variables if the MacOS X version is >= 10.10. In addition there could be options to override, but that way the automatic behavior should be correct in most instances.

**Comment by ghweber** [comment]
On second thought, not doing it by default but having an option for older MacOS versions seems to be the better/less complicated approach).
