### ISSUE TITLE
Partial failure on errors

### ISSUE THREAD

**Issue by mclarsen** [Alpine-DAV/ascent#481]
Currently, if there is an exception from something like a bad filter parameter, the entire execution fails. @kennyweiss requested that we only fail partially, completing all valid paths.

Not sure how we would do this. We would have to be able to kill all all dependent nodes in the execution graph, and we would have to come up with a way to catch all those errors.

**Comment by cyrush** [comment]
I don't think there will be a clean way to do this, if the user asks and we can't deliver b/c of an input error the safest thing to do is error out and ask them to resolve. A mixed out come - some things may have happed, user picks up the pieces themselves - will be painful for both us and folks using the tool.

**Comment by mclarsen** [comment]
Too hard. Will close.

**Comment by kennyweiss** [comment]
I agree with @cyrush -- I don't think ascent should try to recover from a partial error since that could leave things in an inconsistent state.

What I was going for was for ascent not to crash the app that calls ascent.
(and in the context of #475, ascent did the right thing -- it did not crash the calling app).
