### ISSUE TITLE
provide option to set path to file resources for cases when an install is moved 

### ISSUE THREAD

**Issue by cyrush** [Alpine-DAV/ascent#692]
to help resolve:

https://github.com/spack/spack/issues/21739

**Comment by tgamblin** [comment]
Instead of this, if the directory is always fixed, can ascent determine its own prefix?  I am not sure how ascent is typically linked, but you can find the location of a shared library from within that shared lib (see [here](https://stackoverflow.com/questions/43409167/find-location-of-loaded-shared-library-from-in-that-shared-library)).

**Comment by cyrush** [comment]
thanks @tgamblin, I'll look into this. Won't help us when cuda in the mix b/c that requires static libs, but this could help for lots of cases.

**Comment by cyrush** [comment]
to side step the issue completely for cinema -- we are going to compile in these files
